/* This file was automatically generated */
/* by the awk script "sigconv.awk".      */

struct map sigdesc[] = {

    "HUP",	1,
    "INT",	2,
    "QUIT",	3,
    "ILL",	4,
    "TRAP",	5,
    "IOT",	6,
    "ABRT",	6,
    "EMT",	7,
    "FPE",	8,
    "KILL",	9,
    "BUS",	10,
    "SEGV",	11,
    "SYS",	12,
    "PIPE",	13,
    "ALRM",	14,
    "TERM",	15,
    "CLD",	18,
    "CHLD",	18,
    "PWR",	19,
    "WINCH",	20,
    "URG",	21,
    "POLL",	22,
    "STOP",	23,
    "TSTP",	24,
    "CONT",	25,
    "TTIN",	26,
    "TTOU",	27,
    "VTALRM",	28,
    "PROF",	29,
    "XCPU",	30,
    "XFSZ",	31,
    "WAITING",	32,
    "LWP",	33,
    "FREEZE",	34,
    "THAW",	35,
    "CANCEL",	36,
    "LOST",	37,
    (char *) NULL,	 0
};
